langchain4j:
  open-ai:
    chat-model:
      api-key: sk-ws-H.PRRXPML.N1Ge.MEQCIAigCc_9UwrBSZ9OveIDOaFIoAau0E6wmP_iSe7HHEPWAiAOL6LZgQq6tXqaNMezTuJox1uNiDjfeKAIfburEQwd5w
      base-url: https://ws-r0m5urtuko6xd5ob.cn-beijing.maas.aliyuncs.com/compatible-mode/v1
      model-name: qwen3.8-flash
      reasoning-effort: low
      timeout: 600s
      max-retries: 1
      log-responses: true
      log-requests: true
    streaming-chat-model:
      api-key: ${langchain4j.open-ai.chat-model.api-key}
      base-url: ${langchain4j.open-ai.chat-model.base-url}
      model-name: ${langchain4j.open-ai.chat-model.model-name}
      reasoning-effort: ${langchain4j.open-ai.chat-model.reasoning-effort}
      timeout: ${langchain4j.open-ai.chat-model.timeout}
      log-responses: ${langchain4j.open-ai.chat-model.log-responses}
      log-requests: ${langchain4j.open-ai.chat-model.log-requests}
